# Generated by Django 5.0.3 on 2024-07-04 08:31

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('line_amount', models.IntegerField(default=0, validators=[django.core.validators.RegexValidator(message='Seuls les chiffres sont autorisés.', regex='^\\d+$')])),
                ('balance', models.IntegerField(default=0, validators=[django.core.validators.RegexValidator(message='Seuls les chiffres sont autorisés.', regex='^\\d+$')])),
                ('rate_capital', models.FloatField(default=0.0, editable=False, max_length=10)),
                ('debt', models.CharField(max_length=10)),
                ('loan', models.CharField(max_length=10)),
                ('direction', models.CharField(choices=[('bfc', 'bfc'), ('dpws', 'dpws'), ('tsd', 'tsd'), ('bes', 'bes'), ('dex', 'dex')], max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=2024)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
