# Generated by Django 5.0.3 on 2024-07-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_line', '0003_alter_budgetline_rate_capital'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetline',
            options={'ordering': ['name']},
        ),
    ]
