# Generated by Django 5.0.3 on 2024-07-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_line', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetline',
            name='rate_capital',
            field=models.FloatField(default=0.0, editable=False, max_length=3),
        ),
    ]
