# Generated by Django 5.0.3 on 2024-07-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_line', '0002_alter_budgetline_rate_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetline',
            name='rate_capital',
            field=models.CharField(default='0%', max_length=18),
        ),
    ]
