# Generated by Django 5.0.3 on 2024-07-04 08:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget_line', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubLines',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('rate_line', models.FloatField(default=0.0, editable=False, max_length=10)),
                ('rate_capital', models.FloatField(default=0.0, editable=False, max_length=10)),
                ('description', models.CharField(max_length=50)),
                ('used', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Seuls les chiffres sont autorisés.', regex='^\\d+$')])),
                ('id_budget_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sublines', to='budget_line.budgetline')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
