# Generated by Django 5.0.3 on 2024-07-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_lines', '0003_alter_sublines_rate_capital_alter_sublines_rate_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublines',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
