# Generated by Django 5.0.3 on 2024-07-11 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_lines', '0004_sublines_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublines',
            name='updated',
        ),
    ]
