# Generated by Django 5.0.3 on 2024-07-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_lines', '0007_remove_sublines_used_sublines_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sublines',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='sublines',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
