# Generated by Django 5.0.3 on 2024-07-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_lines', '0002_alter_sublines_rate_capital_alter_sublines_rate_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublines',
            name='rate_capital',
            field=models.CharField(default='0%', max_length=18),
        ),
        migrations.AlterField(
            model_name='sublines',
            name='rate_line',
            field=models.CharField(default='0%', max_length=18),
        ),
    ]
