# Generated by Django 5.0.3 on 2024-07-16 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_lines', '0006_alter_sublines_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublines',
            name='used',
        ),
        migrations.AddField(
            model_name='sublines',
            name='balance',
            field=models.IntegerField(default=0, validators=[django.core.validators.RegexValidator(message='Seuls les chiffres sont autorisés.', regex='^\\d+$')]),
        ),
    ]
